# Site settings
title: Another day
header-img: img/home-bg.png
email: jeffreyerickatz@gmail.com
copyright_name: JeffKatzy
description: > # this means to ignore newlines until "baseurl:"
  It was better
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: @jeffkatzy
github_username:  JeffKatzy
learn_profile: JeffKatzy
email_username: jeffreyerickatz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
